language: python
python:
  - "3.6"
install:
  - apt-get install -y default-jre
  - yarn install
  - yarn run test-db &
  - sleep 5
  - pip install pipenv
  - pipenv install --dev --system
script:
  - pytest --cov-config=.coveragerc --ignore=vuemail-dark
after_script:
  - coverage report